image: Visual Studio 2019
clone_depth: 1

init:
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=1
  - set PATH=C:\msys64\usr\bin;%PATH%
  - 
install:
  - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"



build_script:
  - bash -lc "pushd C:\projects\kalibrate-rtl; ./configure"
 
 # on_failure:
 
cache:
  - c:\msys2