image: Visual Studio 2019
clone_depth: 1

init:
  - set APPVEYOR_SAVE_CACHE_ON_ERROR=1

install:
  - ls C:\
  - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"



build_script:
  - bash -c "./configure"
 
 # on_failure:
 
cache:
  - c:\msys2